### ISSUE TITLE
gulp symLinkTheme fails in some situations

### ISSUE THREAD

**Issue by aleksip** [NatLibFi/NDL-VuFind-ui-components#60]
```
$ gulp symLinkTheme
[12:27:44] Using gulpfile ~/Sites/NDL-VuFind-ui-components/gulpfile.js
[12:27:44] Starting 'symLinkTheme'...
[12:27:44] Starting 'shouldRemoveComponents'...
[12:27:44] 'shouldRemoveComponents' errored after 894 μs
[12:27:44] Error: ENOENT: no such file or directory, lstat '/Users/peebles/Sites/NDL-VuFind2/themes/finna2/js/components'
    at Object.lstatSync (fs.js:923:3)
    at /Users/peebles/Sites/NDL-VuFind-ui-components/gulp-helpers.js:20:22
    at Array.filter (<anonymous>)
    at symlinksExist (/Users/peebles/Sites/NDL-VuFind-ui-components/gulp-helpers.js:19:16)
    at Object.checkForComponents (/Users/peebles/Sites/NDL-VuFind-ui-components/gulp-helpers.js:33:36)
    at shouldRemoveComponents (/Users/peebles/Sites/NDL-VuFind-ui-components/gulpfile.js:272:38)
    at bound (domain.js:426:14)
    at runBound (domain.js:439:12)
    at asyncRunner (/Users/peebles/Sites/NDL-VuFind-ui-components/node_modules/async-done/index.js:55:18)
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
```

@mikkojamG

**Comment by aleksip** [comment]
```
$ gulp copyTheme
[15:51:22] Using gulpfile ~/Sites/NDL-VuFind-ui-components/gulpfile.js
[15:51:22] Starting 'copyTheme'...
[15:51:22] Starting 'shouldUnlinkTheme'...
✔ The working theme has pre-existing linked components. Would you like to unlink the components? … yes
[15:51:26] Starting 'unlinkPatterns'...
[15:51:26] Finished 'shouldUnlinkTheme' after 3.73 s
[15:51:26] Starting 'copyPatterns'...
[15:51:26] Finished 'unlinkPatterns' after 18 ms
[15:51:26] Starting 'unlinkStyles'...
[15:51:26] Finished 'unlinkStyles' after 18 ms
[15:51:26] Starting 'unlinkScripts'...
[15:51:26] Finished 'unlinkScripts' after 13 ms
[15:51:26] Finished 'copyPatterns' after 91 ms
[15:51:26] Starting 'copyStyles'...
[15:51:26] Finished 'copyStyles' after 34 ms
[15:51:26] Starting 'copyScripts'...
[15:51:26] Finished 'copyScripts' after 19 ms
[15:51:26] Starting 'themeLessImports'...
[15:51:26] Finished 'themeLessImports' after 533 μs
[15:51:26] Starting 'themeScriptImports'...
[15:51:26] Finished 'themeScriptImports' after 301 μs
[15:51:26] Finished 'copyTheme' after 3.87 s
$ gulp symLinkTheme
[15:51:32] Using gulpfile ~/Sites/NDL-VuFind-ui-components/gulpfile.js
[15:51:32] Starting 'symLinkTheme'...
[15:51:32] Starting 'shouldRemoveComponents'...
✔ The working theme has pre-existing components. Would you like to remove the components and link instead? … yes
[15:51:34] Starting 'unlinkPatterns'...
[15:51:34] Finished 'shouldRemoveComponents' after 1.38 s
[15:51:34] Starting 'symLinkPatterns'...
[15:51:34] Finished 'unlinkPatterns' after 16 ms
[15:51:34] Starting 'unlinkStyles'...
[15:51:34] 'symLinkPatterns' errored after 20 ms
[15:51:34] Error: exited with error code: 1
    at ChildProcess.onexit (/Users/peebles/Sites/NDL-VuFind-ui-components/node_modules/end-of-stream/index.js:40:36)
    at ChildProcess.emit (events.js:321:20)
    at ChildProcess.EventEmitter.emit (domain.js:505:15)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
[15:51:34] 'symLinkTheme' errored after 1.4 s
[15:51:34] The following tasks did not complete: unlinkStyles
[15:51:34] Did you forget to signal async completion?
```
